# Generated by Django 3.0.3 on 2020-05-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentimage',
            name='image_filename',
            field=models.ImageField(null=True, upload_to='news/images/comment'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_filename',
            field=models.ImageField(null=True, upload_to='news/images/post'),
        ),
    ]
