# Generated by Django 3.0.3 on 2020-05-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200506_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_slug',
        ),
    ]
