# Generated by Django 3.0.3 on 2020-05-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_post_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_post',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Post'),
        ),
    ]
