# Generated by Django 3.0.3 on 2020-05-07 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200507_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
