# Generated by Django 3.0.3 on 2020-05-07 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200507_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentImage',
        ),
    ]
