# Generated by Django 3.0.3 on 2020-05-11 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
